# Generated by Django 4.2.30 on 2026-09-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
