# Generated by Django 4.2.30 on 2026-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
