# Generated by Django 4.2.30 on 2026-09-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_emailverificationcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='session_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
