# Generated by Django 4.2.30 on 2026-09-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customerprofile_session_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='verification_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='verification_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
