# Generated by Django 4.2.30 on 2026-09-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='brevo_campaign_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='template_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
