# Generated by Django 4.2.30 on 2026-09-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newslettercampaign_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='audience_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='recipient_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='recipient_type',
            field=models.CharField(default='subscribers', max_length=50),
        ),
    ]
