# Generated by Django 4.2.30 on 2026-09-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newslettercampaign_audience_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='content_image',
            field=models.URLField(blank=True),
        ),
    ]
