# Generated by Django 4.2.30 on 2026-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='VELRA', max_length=200)),
                ('store_email', models.EmailField(blank=True, max_length=254)),
                ('store_phone', models.CharField(blank=True, max_length=30)),
                ('store_address', models.TextField(blank=True)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
