# Generated by Django 4.2.30 on 2026-09-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['state']},
        ),
    ]
