# Generated by Django 4.2.30 on 2026-09-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shippingrate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['delivery_type', 'state']},
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='delivery_type',
            field=models.CharField(choices=[('state', 'State'), ('pickup', 'Pickup')], default='state', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='pickup_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
