# Generated by Django 4.2.30 on 2026-09-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_shippingrate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['delivery_type', 'state', 'city']},
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
