# Generated by Django 4.2.30 on 2026-09-23 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_method_order_pickup_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
