# Generated by Django 4.2.30 on 2026-09-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_checkout_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preorder_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preorder_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
