# Generated by Django 4.2.30 on 2026-09-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_is_preorder_orderitem_preorder_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
