# Generated by Django 4.2.30 on 2026-09-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(blank=True, choices=[('edp', 'Eau de Parfum (EDP)'), ('edt', 'Eau de Toilette (EDT)'), ('parfum', 'Parfum / Extrait'), ('edc', 'Eau de Cologne (EDC)'), ('mist', 'Body Mist')], max_length=20),
        ),
    ]
