# Generated by Django 4.2.30 on 2026-09-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
